requirements.txt
tox.ini

This fixes errors when executing tox automation tests. Requirements are already addded to one place (tox.ini or requirements.txt)

Fix duplicated requirements

---

requirements.txt
tox.ini

This requirement on tox.ini made the charm pass CI but fail if built manually

Move requirement to requirements file

---

src/charm.py
src/cluster.py
src/config.py
src/provider.py
src/tls.py
tests/integration/test_tls.py
tests/unit/test_config.py
tests/unit/test_provider.py
tests/unit/test_tls.py
tox.ini

- Previous implementation mistakenly skipped the `portUnification`+`sslQuorum` step when switching to SSL quorum encryption, sometimes resulting in loss of quorum
- This had a knock-on effect, where only a single-server quorum was left, and when a client related to the ZK app, that server would restart and not be part of a quorum 
- Fixed by setting unit + app level relation data checking that all units are at the correct stage of an encryption change, before doing anything else
- Previous implementation mistakenly overwrote the dynamic property set in `zookeeper.properties` to set new SSL-specific config, sometimes resulting in loss of quorum
- This resulted in servers sometimes not being aware of other server members after restarting, losing quorum  
- Fixed by checking current …

fix: ensure quorum not lost during tls relation + client ports update

---

src/charm.py
src/provider.py
src/tls.py
src/utils.py
tests/unit/test_charm.py
tests/unit/test_client.py
tests/unit/test_cluster.py
tests/unit/test_config.py
tests/unit/test_provider.py
tests/unit/test_tls.py

- Due to active development, there were no unittests for `charm.py`. These have been added
- Added additional `cluster.py` and `tls.py` tests to add coverage for new features
- Please focus on `tests/unit/test_charm.py`
- There are a lot of tests, so most help would be whether any were implemented incorrectly from an `ops.testing` standpoint

test: introduce charm.py unittest coverage

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
CONTRIBUTING.md
pyproject.toml
tests/__init__.py
tests/integration/conftest.py
tests/integration/test_password_rotation.py
tests/integration/test_provider.py
tests/integration/test_scaling.py
tests/integration/test_tls.py
tests/unit/__init__.py
tox.ini

Ported from https://github.com/canonical/mysql-k8s-operator/pull/146

Cache charmcraft pack container, skip unstable tests except on schedule

---

config.yaml
metadata.yaml
src/config.py
src/literals.py
src/tls.py
tests/integration/helpers.py
tests/unit/test_config.py

Blocked by https://github.com/canonical/zookeeper-rock/pull/15. Until it's merged, all tests will fail.
- Removed these options from `config.yaml`

refactor: use new charmed-zookeeper image and layout

---

metadata.yaml

Addressing https://warthogs.atlassian.net/browse/DPE-1901
We want to bind each charm (Zookeeper, Kafka) on both substrate (K8s, VM) with pinned snap revision and rocks hashes.
Take inspiration from mysql 
* [VM](https://github.com/canonical/mysql-operator/blob/main/src/constants.py#L27)
* [K8s](https://github.com/canonical/mysql-k8s-operator/blob/main/metadata.yaml#L36)
All charms are pinned to snap revision and rock hashes

[DPE-1901] Bind pinned image revision

---

src/charm.py
tests/integration/ha/conftest.py
tests/integration/ha/helpers.py
tests/integration/ha/manifests/chaos_network_loss.yaml
tests/integration/ha/scripts/deploy_chaos_mesh.sh
tests/integration/ha/scripts/destroy_chaos_mesh.sh
tests/integration/ha/test_ha.py

- Uses the `ruok` 4lw command to ping the local ZooKeeper server
- Defaults to `period=10s` and `threshold=3` as per the [Pebble specification](https://github.com/canonical/pebble#layer-specification)
- If fails, container is restarted as per [K8s specification](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-command)

DPE-2639 - test: add network cut test

---

tests/integration/ha/helpers.py
tests/integration/ha/manifests/extend_pebble_restart_delay.yaml
tests/integration/ha/manifests/restore_pebble_restart_delay.yaml
tests/integration/ha/test_ha.py

test: add ha full cluster crash tests

---

metadata.yaml
tests/integration/ha/helpers.py
tests/integration/ha/test_ha.py

- Storage volume was mounted to the `charm` container, not to the `workload`. As such, storage wasn't actually persisted
- Resolved by persisting `data` and `data-log` dirs under `/var/lib/zookeeper`
- Although advice is to mount transactions + snapshots on different volumes for IO performance, Juju supports only a single volume. As ZooKeeper uses the Txn log to re-build snapshots after data loss, it's a trade-off for now
- Checks for existence of 'old' files after a scale-down + up
- If 'old' files present, storage was re-used

DPE-2710 - test: add storage scale down/up storage re-use test

---

src/events/provider.py
src/managers/config.py
src/managers/quorum.py
tests/integration/test_provider.py
tests/unit/test_provider.py
tests/unit/test_quorum.py

- Mistake from the refactor meant that on `relation-broken` events, the `chroot` from the broken Application would still exist, with it's zNodes surviving the break
- Removing a Kafka relation, then re-relating, would persist the original ACLs (e.g `relation-6`) on child nodes (e.g `/kafka/config/users`) sharing the same parent (e.g `/kafka`)
- This meant that the related application couldn't authenticate to the new zNodes

fix: properly remove old zNodes during relation-broken

---

src/managers/quorum.py
tests/unit/test_quorum.py

- Found when relating applications to ZooKeeper too quickly before cluster init, ZooKeeper will read an empty value for `client.chroot` and attempt to add it, resulting in a `NodeExistsError` from Kazoo
- Now, we skip setting anything if `client.chroot` does not exist
- Also made the chroot logging `INFO` level, for more clarity of what's happening

fix: skip empty chroot adding

---

src/charm.py
src/events/upgrade.py
tests/unit/conftest.py
tests/unit/test_charm.py
tests/unit/test_upgrade.py

- Moved to dedicated method
- `config_changed` setting of config items is now skipped, avoiding issues with missing new relation-data items
- Juju status setting should now be skipped on `update-status`, meaning that the charm will stay `BlockedStatus` if upgrade failed

fix: skip relation-changed if upgrading

---

metadata.yaml
src/charm.py
src/core/workload.py
src/managers/config.py

OCI image is now updated with correct bin and log paths. Addresses #68 
NOTE: moved pebble layer declaration to `charm.py` for two reasons:
1. Pebble layer definition is strictly tied to k8s charms, so I woudn't consider it common/shared code.
2. Changing layer is a k8s only task, being in `managers.config` any change would need to be backported to vm. Like the one on this PR.
Thoughts on this?

[DPE-3479] Update image and paths

---

src/workload.py

The change introduced in #84 would make integration tests flaky, because pebble commands would be issued before the service was launched

[DPE-3783] Add alive check in get_version

---

pyproject.toml
src/events/tls.py
src/literals.py
src/managers/config.py
src/managers/tls.py
tests/integration/test_tls.py
tests/unit/test_tls.py

- Enable `sslQuorumReloadCertFiles` and `client.certReload` to dynamically reload the trust and key store for both quorum and client TLS. Removed restart event emission.
- Removed `ssl.client.enable` which is not a ZooKeeper configuration option.
- Replace stores content upon new certificate available. The code is a little too nested for my tastes, but IMO still understandable. I can always extract the innermost code into a `_replace_ca_in_truststore` method if needed

[DPE-3477] Reload stores

---

lib/charms/zookeeper/v0/client.py
src/managers/config.py
src/managers/quorum.py
tests/unit/test_config.py

- Was a new feature in [ZooKeeper 3.7](https://zookeeper.apache.org/doc/r3.9.2/zookeeperAdmin.html#sc_authOptions)

[DPE-5208] - fix: enforce client auth

---

actions.yaml
src/charm.py
src/core/cluster.py
src/core/models.py
src/core/stubs.py
src/core/workload.py
src/events/backup.py
src/events/provider.py
src/literals.py
src/managers/backup.py
src/managers/config.py
src/managers/quorum.py
tests/integration/test_backup.py
tests/unit/scenario/test_backup.py
tests/unit/test_charm.py
tests/unit/test_config.py
tests/unit/test_quorum.py
tests/unit/test_upgrade.py

See https://github.com/canonical/zookeeper-operator/pull/162 for rationale and explanations.

[DPE-5218] Implement restore flow

---

src/events/upgrade.py
src/managers/tls.py
tests/integration/__init__.py
tests/integration/test_tls.py
tests/integration/test_upgrade.py

- Resolved by adding backwards compatibility fix
- Sometimes caused units to go in to error

fix: failing upgrades without chain

---

.readthedocs.yaml
docs/conf.py
docs/content/how-to/index.md
docs/index.md

ReadTheDocs config change to fix builds fail with warning messages for too shallow clone.

[Docs] Fix the docs build error for shallow clone 
